server:
  port: 8001

  spring:
    application:
      name: microservicecloud-dept

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.wangx.springcloud.entities # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml # mapper映射文件
Spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源朝着类型
    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    url: jdbc:mysql://111.229.185.144:3306/cloudDb01?useUnicode=true&characterEncoding=utf-8&useSSL=false # 数据库名称 useSSL=false 5.7以后已经进行了安全加固不加这个可能会报错
    username: root
    password: woshiwang1094
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初试化连接数据
      max-total: 5 # 最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间