
package com.wangx.webservice.webserviceCXFJaxws.serialization;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IWebSvc", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        com.wangx.webservice.webserviceCXFJaxws.serialization.ObjectFactory.class,
        com.wangx.webservice.webserviceCXFJaxws.serialization.ObjectFactory.class
})
public interface IWebSvc {


    /**
     * @param data
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "Run", action = "http://tempuri.org/IWebSvc/Run")
    @WebResult(name = "RunResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Run", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Run")
    @ResponseWrapper(localName = "RunResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RunResponse")
    public String run(
            @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
                    String data);

}
