server:
  port: 3344

spring:
  application:
    name: microservicecloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/price0147/SpringcloudConfig.git #GitHub上面的git仓库名字
          ###搜索目录
          search-paths:
            - springcloud-config
      ###读取分支
      label: master

#服务注册到eureka
eureka:
    client:
      service-url:
        defaultZone: http://localhost:7001/eureka